kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "devshop.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.frontend.env.ENVIRONMENT | quote }}
  FRONTEND_PORT: {{ .Values.frontend.service.targetPort | quote }}
  GATEWAY_PORT: {{ .Values.gateway.service.targetPort | quote }}
  PRODUCTS_PORT: {{ .Values.products.service.targetPort | quote }}
  ORDERS_PORT: {{ .Values.orders.service.targetPort | quote }}

  API_GATEWAY_URL: http://{{ include "devshop.fullname" (dict "name" "gateway" "context" .) }}:{{ .Values.gateway.service.port }}
  PRODUCTS_SERVICE_URL: http://{{ include "devshop.fullname" (dict "name" "products" "context" .) }}:{{ .Values.products.service.port }}
  ORDERS_SERVICE_URL: http://{{ include "devshop.fullname" (dict "name" "orders" "context" .) }}:{{ .Values.orders.service.port }}
