apiVersion: v1
kind: Service
metadata:
  name: {{ include "devshop.fullname" (dict "name" "products" "context" .) }}
  labels:
    {{- include "devshop.labels" . | nindent 4}}
    app.kubernetes.io/name: products
spec:
  type: {{ .Values.products.service.type }}
  ports:
  - port: {{ .Values.products.service.port }}
    targetPort: {{ .Values.products.service.targetPort }}
    name: http
  selector:
    {{- include "devshop.selectorLabels" (dict "name" "products" "context" .)| nindent 4 }}
