apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  MONGO_URI: {{ include "devshop.mongodbUri" . | quote }}
  REDIS_URL: {{ include "devshop.redisUrl" . | quote }}
